# Russian name translation data for dev_scripts/translate_names.py.
#
# Most of the ~14k names are combinatorial move names: [modifiers...] HEAD.
# ADJ gives Russian adjective forms (m, f, n) agreeing with the head noun's
# gender; HEAD gives the Russian head noun(s) and gender index (0=m, 1=f, 2=n).
# POSS gives genitive forms for "X's Y" names (X's Beak -> 'Клюв журавля').
# Everything non-compositional (styles, techs, items, weapons, traits,
# accomplishments, special move names) lives in OVERRIDES.

ADJ = {
    'Acrobatic': ('Акробатический', 'Акробатическая', 'Акробатическое'),
    'Advanced': ('Продвинутый', 'Продвинутая', 'Продвинутое'),
    'Air': ('Воздушный', 'Воздушная', 'Воздушное'),
    'Astral': ('Астральный', 'Астральная', 'Астральное'),
    'Attacking': ('Атакующий', 'Атакующая', 'Атакующее'),
    'Avalanche': ('Лавинный', 'Лавинная', 'Лавинное'),
    'Averting': ('Уклончивый', 'Уклончивая', 'Уклончивое'),
    'Balanced': ('Уравновешенный', 'Уравновешенная', 'Уравновешенное'),
    'Bizarre': ('Причудливый', 'Причудливая', 'Причудливое'),
    'Burning': ('Пылающий', 'Пылающая', 'Пылающее'),
    'Cautious': ('Осторожный', 'Осторожная', 'Осторожное'),
    'Charging': ('Рвущийся', 'Рвущаяся', 'Рвущееся'),
    'Clinging': ('Цепкий', 'Цепкая', 'Цепкое'),
    'Dancing': ('Танцующий', 'Танцующая', 'Танцующее'),
    'Deadly': ('Смертельный', 'Смертельная', 'Смертельное'),
    'Debilitating': ('Ослабляющий', 'Ослабляющая', 'Ослабляющее'),
    'Defending': ('Защитный', 'Защитная', 'Защитное'),
    'Drunken': ('Пьяный', 'Пьяная', 'Пьяное'),
    'Earth': ('Земляной', 'Земляная', 'Земляное'),
    'Elusive': ('Неуловимый', 'Неуловимая', 'Неуловимое'),
    'Emerald': ('Изумрудный', 'Изумрудная', 'Изумрудное'),
    'Energy': ('Энергетический', 'Энергетическая', 'Энергетическое'),
    'Exotic': ('Экзотический', 'Экзотическая', 'Экзотическое'),
    'Expert': ('Экспертный', 'Экспертная', 'Экспертное'),
    'Fast': ('Быстрый', 'Быстрая', 'Быстрое'),
    'Ferocious': ('Свирепый', 'Свирепая', 'Свирепое'),
    'Fire': ('Огненный', 'Огненная', 'Огненное'),
    'Flying': ('Летающий', 'Летающая', 'Летающее'),
    'Formless': ('Бесформенный', 'Бесформенная', 'Бесформенное'),
    'Furious': ('Яростный', 'Яростная', 'Яростное'),
    'Grappling': ('Борцовский', 'Борцовская', 'Борцовское'),
    'Guarding': ('Сторожевой', 'Сторожевая', 'Сторожевое'),
    'Heavenly': ('Небесный', 'Небесная', 'Небесное'),
    'Heavy': ('Тяжёлый', 'Тяжёлая', 'Тяжёлое'),
    'Ice': ('Ледяной', 'Ледяная', 'Ледяное'),
    'Indestructible': ('Несокрушимый', 'Несокрушимая', 'Несокрушимое'),
    'Invulnerable': ('Неуязвимый', 'Неуязвимая', 'Неуязвимое'),
    'Iron': ('Железный', 'Железная', 'Железное'),
    'Kicking': ('Ножной', 'Ножная', 'Ножное'),
    'Lethal': ('Смертоносный', 'Смертоносная', 'Смертоносное'),
    'Light': ('Лёгкий', 'Лёгкая', 'Лёгкое'),
    'Light-Footed': ('Легконогий', 'Легконогая', 'Легконогое'),
    'Lightning': ('Молниеносный', 'Молниеносная', 'Молниеносное'),
    'Long': ('Длинный', 'Длинная', 'Длинное'),
    'Long-Range': ('Дальнобойный', 'Дальнобойная', 'Дальнобойное'),
    'Meteor': ('Метеорный', 'Метеорная', 'Метеорное'),
    'Mid-Range': ('Среднедистанционный', 'Среднедистанционная', 'Среднедистанционное'),
    'Misty': ('Туманный', 'Туманная', 'Туманное'),
    'Moon': ('Лунный', 'Лунная', 'Лунное'),
    'Mystic': ('Мистический', 'Мистическая', 'Мистическое'),
    'Nerve': ('Нервный', 'Нервная', 'Нервное'),
    'Nimble': ('Проворный', 'Проворная', 'Проворное'),
    'Northern': ('Северный', 'Северная', 'Северное'),
    'Obsidian': ('Обсидиановый', 'Обсидиановая', 'Обсидиановое'),
    'Onslaught': ('Напористый', 'Напористая', 'Напористое'),
    'Open-Handed': ('Ладонный', 'Ладонная', 'Ладонное'),
    'Paralyzing': ('Парализующий', 'Парализующая', 'Парализующее'),
    'Persevering': ('Упорный', 'Упорная', 'Упорное'),
    'Piercing': ('Пронзающий', 'Пронзающая', 'Пронзающее'),
    'Power': ('Силовой', 'Силовая', 'Силовое'),
    'Powerful': ('Мощный', 'Мощная', 'Мощное'),
    'Precise': ('Точный', 'Точная', 'Точное'),
    'Punching': ('Кулачный', 'Кулачная', 'Кулачное'),
    'Pushing': ('Толкающий', 'Толкающая', 'Толкающее'),
    'Quick': ('Скорый', 'Скорая', 'Скорое'),
    'Rainbow': ('Радужный', 'Радужная', 'Радужное'),
    'Razor': ('Бритвенный', 'Бритвенная', 'Бритвенное'),
    'Red': ('Красный', 'Красная', 'Красное'),
    'Retaliating': ('Ответный', 'Ответная', 'Ответное'),
    'Retreating': ('Отступающий', 'Отступающая', 'Отступающее'),
    'Rising': ('Восходящий', 'Восходящая', 'Восходящее'),
    'Sharp': ('Острый', 'Острая', 'Острое'),
    'Shattering': ('Сокрушительный', 'Сокрушительная', 'Сокрушительное'),
    'Shocking': ('Шокирующий', 'Шокирующая', 'Шокирующее'),
    'Short': ('Короткий', 'Короткая', 'Короткое'),
    'Skillful': ('Искусный', 'Искусная', 'Искусное'),
    'Slashing': ('Рубящий', 'Рубящая', 'Рубящее'),
    'Snow': ('Снежный', 'Снежная', 'Снежное'),
    'Solar': ('Солнечный', 'Солнечная', 'Солнечное'),
    'Spiky': ('Колючий', 'Колючая', 'Колючее'),
    'Stinging': ('Жалящий', 'Жалящая', 'Жалящее'),
    'Stone': ('Каменный', 'Каменная', 'Каменное'),
    'Storm': ('Грозовой', 'Грозовая', 'Грозовое'),
    'Strong': ('Сильный', 'Сильная', 'Сильное'),
    'Sun': ('Солнечный', 'Солнечная', 'Солнечное'),
    'Super': ('Супер', 'Супер', 'Супер'),
    'Superior': ('Превосходный', 'Превосходная', 'Превосходное'),
    'Surprise': ('Внезапный', 'Внезапная', 'Внезапное'),
    'Swift': ('Стремительный', 'Стремительная', 'Стремительное'),
    'Swift-Striking': ('Молниеносный', 'Молниеносная', 'Молниеносное'),
    'Tipsy': ('Подвыпивший', 'Подвыпившая', 'Подвыпившее'),
    'Tough': ('Крепкий', 'Крепкая', 'Крепкое'),
    'Trick': ('Обманный', 'Обманная', 'Обманное'),
    'Twisting': ('Извивающийся', 'Извивающаяся', 'Извивающееся'),
    'Ultimate': ('Высший', 'Высшая', 'Высшее'),
    'Ultra': ('Ультра', 'Ультра', 'Ультра'),
    'Unstoppable': ('Неостановимый', 'Неостановимая', 'Неостановимое'),
    'Vanishing': ('Исчезающий', 'Исчезающая', 'Исчезающее'),
    'Vengeful': ('Мстительный', 'Мстительная', 'Мстительное'),
    'Venom': ('Ядовитый', 'Ядовитая', 'Ядовитое'),
    'Vigorous': ('Энергичный', 'Энергичная', 'Энергичное'),
    'Water': ('Водяной', 'Водяная', 'Водяное'),
    'White': ('Белый', 'Белая', 'Белое'),
    'Wind': ('Ветреный', 'Ветреная', 'Ветреное'),
    'Wooden': ('Деревянный', 'Деревянная', 'Деревянное'),
}

HEAD = {
    'Breath': ('дыхание', 2),
    'Claw': ('коготь', 0),
    'Elbow': ('удар локтем', 0),
    'Energy': ('энергия', 1),
    'Fist': ('кулак', 0),
    'Form': ('форма', 1),
    'Forms': ('формы', 1),
    'Guard': ('блок', 0),
    'Headbutt': ('удар головой', 0),
    'Jump': ('прыжок', 0),
    'Kick': ('удар ногой', 0),
    'Knee': ('удар коленом', 0),
    'Leap': ('прыжок', 0),
    'Onslaught': ('натиск', 0),
    'Palm': ('удар ладонью', 0),
    'Power': ('мощь', 1),
    'Punch': ('удар кулаком', 0),
    'Stance': ('стойка', 1),
    'Step': ('шаг', 0),
    'Strike': ('удар', 0),
    'Strikes': ('удары', 0),
    'Sweep': ('подсечка', 1),
    'Throw': ('бросок', 0),
    'Trip': ('подножка', 1),
}

POSS = {
    "Bear's": 'медведя',
    "Beggar's": 'нищего',
    "Brawler's": 'задиры',
    "Cat's": 'кота',
    "Dragon's": 'дракона',
    "Earth's": 'земли',
    "Elephant's": 'слона',
    "Emperor's": 'императора',
    "Hero's": 'героя',
    "Lion's": 'льва',
    "Moon's": 'луны',
    "Ox's": 'быка',
    "Squirrel's": 'белки',
    "Sun's": 'солнца',
    "Thief's": 'вора',
    "Tiger's": 'тигра',
    "Toad's": 'жабы',
    "Turtle's": 'черепахи',
}

OVERRIDES = {
    # -- kung-fu styles (handcrafted) --
    'Bagua Zhang': 'Багуа Чжан',
    'Balanced Fist': 'Уравновешенный кулак',
    'Centipede': 'Многоножка',
    'Choy Li Fut': 'Чой Ли Фут',
    'Dragon': 'Дракон',
    'Drunken Boxing': 'Пьяный бокс',
    'Eagle Claw': 'Коготь орла',
    'Eight Extremities Fist': 'Кулак восьми пределов',
    'Gecko': 'Геккон',
    'Hung Ga': 'Хун Гар',
    'Leopard': 'Леопард',
    'Long Fist': 'Длинный кулак',
    'Monkey': 'Обезьяна',
    'Poking Foot': 'Тычковая нога',
    'Praying Mantis': 'Богомол',
    'Scorpion': 'Скорпион',
    'Shaolin Fist': 'Шаолиньский кулак',
    'Snake': 'Змея',
    'Taiji': 'Тайцзи',
    'Tiger': 'Тигр',
    'Toad': 'Жаба',
    'White Crane': 'Белый журавль',
    'Wing Chun': 'Вин Чун',
    'Xing Yi': 'Синъи',
    "Beggar's Fist": 'Кулак нищего',
    "Thief's Shadow": 'Тень вора',
    'Drunken Dragon': 'Пьяный дракон',
    'Turtle Ninjutsu': 'Ниндзюцу черепахи',
    'Flower Kung-fu': 'Цветочное кунг-фу',
    'Dirty Fighting': 'Грязный бой',
    'Police Kung-fu': 'Полицейское кунг-фу',
    'Monster Kung-fu': 'Кунг-фу монстра',
    'Savant': 'Савант',
    'No Style': 'Без стиля',
    'English Boxing': 'Английский бокс',
    'Wrestling': 'Борьба',
    'Karate': 'Карате',
    'Taekwondo': 'Тхэквондо',
    'Muai Thai': 'Муай-тай',
    'Capoeira': 'Капоэйра',
    # -- items --
    'Ginseng Root': 'Корень женьшеня',
    'Tiger Herb': 'Тигровая трава',
    'Super Tiger Herb': 'Супер тигровая трава',
    'Monkey Herb': 'Обезьянья трава',
    'Super Monkey Herb': 'Супер обезьянья трава',
    'Fly Herb': 'Мушиная трава',
    'Super Fly Herb': 'Супер мушиная трава',
    'Dragon Herb': 'Драконья трава',
    'Super Dragon Herb': 'Супер драконья трава',
    'Elephant Herb': 'Слоновья трава',
    'Super Elephant Herb': 'Супер слоновья трава',
    'Ox Herb': 'Бычья трава',
    'Super Ox Herb': 'Супер бычья трава',
    'Super Mega Herb': 'Супер мега трава',
    'wooden mannequin': 'деревянный манекен',
    'constipation medicine': 'лекарство от запора',
    'cough medicine': 'лекарство от кашля',
    'culinary herb mix': 'кулинарная смесь трав',
    # -- weapons --
    'pair of swords': 'пара мечей',
    'saber': 'сабля',
    'spear': 'копьё',
    'staff': 'посох',
    'sword': 'меч',
    'fan': 'веер',
    'chopsticks': 'палочки для еды',
    'broom': 'метла',
    'stick': 'палка',
    'pole': 'шест',
    'umbrella': 'зонт',
    'bench': 'скамья',
    'chair': 'стул',
    'guqin': 'гуцинь',
    'hammer': 'молот',
    'cloth': 'ткань',
    'rope': 'верёвка',
    'chain': 'цепь',
    'axe': 'топор',
    'bludgeon': 'дубина',
    'knife': 'нож',
    'baton': 'дубинка',
    # -- weapon moves --
    'Saber Slash': 'Взмах саблей',
    'Saber Thrust': 'Выпад саблей',
    'Long Spear Thrust': 'Длинный выпад копьём',
    'Spear Thrust': 'Выпад копьём',
    'Staff Strike': 'Удар посохом',
    'Sword Slash': 'Взмах мечом',
    'Sword Thrust': 'Выпад мечом',
    'Pair of Swords Slash': 'Взмах пары мечей',
    'Pair of Swords Stab': 'Укол пары мечей',
    'Fan Strike': 'Удар веером',
    'Chopsticks Thrust': 'Выпад палочками',
    'Broom Strike': 'Удар метлой',
    'Broom Thrust': 'Выпад метлой',
    'Stick Strike': 'Удар палкой',
    'Stick Thrust': 'Выпад палкой',
    'Pole Strike': 'Удар шестом',
    'Pole Thrust': 'Выпад шестом',
    'Umbrella Strike': 'Удар зонтом',
    'Umbrella Thrust': 'Выпад зонтом',
    'Bench Smash': 'Тяжёлый удар скамьёй',
    'Chair Smash': 'Тяжёлый удар стулом',
    'Guqin Smash': 'Тяжёлый удар гуцинем',
    'Hammer Smash': 'Тяжёлый удар молотом',
    'Hammer Strike': 'Удар молотом',
    'Cloth Whip': 'Хлыст тканью',
    'Rope Whip': 'Хлыст верёвкой',
    'Chain Whip': 'Хлыст цепью',
    'Axe Chop': 'Рубящий удар топором',
    'Axe Slash': 'Взмах топором',
    'Bludgeon Smash': 'Тяжёлый удар дубиной',
    'Bludgeon Strike': 'Удар дубиной',
    'Knife Stab': 'Укол ножом',
    'Knife Slash': 'Взмах ножом',
    'Baton Smash': 'Тяжёлый удар дубинкой',
    'Baton Strike': 'Удар дубинкой',
    # -- traits --
    'narrow-minded': 'недалёкий',
    'broad-minded': 'широких взглядов',
    'quick-witted': 'сообразительный',
    'slow-witted': 'тугодум',
    'cowardly': 'трусливый',
    'brave': 'храбрый',
    'friendly': 'дружелюбный',
    'unfriendly': 'недружелюбный',
    'generous': 'щедрый',
    'greedy': 'жадный',
    'hardworking': 'трудолюбивый',
    'lazy': 'ленивый',
    'disciplined': 'дисциплинированный',
    'undisciplined': 'недисциплинированный',
    'careful': 'осторожный',
    'careless': 'беспечный',
    # -- group names / fighter-name prefixes / misc display names --
    'Thug 1': 'Головорез 1',
    'Robber 1': 'Разбойник 1',
    'Thugs': 'Головорезы',
    'Robbers': 'Разбойники',
    'Beggar': 'Нищий',
    'Drunkard': 'Пьяница',
    'Thief': 'Вор',
    'Master': 'Мастер',
    'Unknown': 'Неизвестный',
    'Gang Leader': 'Главарь банды',
    'Foshan': 'Фошань',
    # -- victory conditions --
    'Grandmaster': 'Гроссмейстер',
    'Folk Hero': 'Народный герой',
    'Famous Master': 'Знаменитый мастер',
    'Living Legend': 'Живая легенда',
    'Master of Masters': 'Мастер мастеров',
    'Kung-fu Legend': 'Легенда кунг-фу',
    'Greatest Fighter': 'Величайший боец',
    'Uniter of Schools': 'Объединитель школ',
    # -- accomplishments --
    'Beat Self': 'Победа над собой',
    'Grand Melee Champion': 'Чемпион большой свалки',
    'King of the Night Ring': 'Король ночного ринга',
    'Beat Bandit Fiance': 'Побит жених-бандит',
    'Foreign Challenger': 'Иностранный претендент',
    'National Treasures': 'Национальные сокровища',
    'Pouch Justice': 'Возмездие за кошелёк',
    'School Defender': 'Защитник школы',
    'Jade Table': 'Нефритовый стол',
    'TMNT': 'Черепашки-ниндзя',
    'All-Schools Champion': 'Чемпион всех школ',
    'Renowned Master': 'Прославленный мастер',
    'Rescued Sweetheart': 'Спасение любимого человека',
    'Eight Gates': 'Восемь врат',
    'Riot Survivor': 'Переживший бунт',
    'Founder of the Federation': 'Основатель федерации',
    'Unlucky Devil': 'Невезучий чёрт',
    'Lucky Devil': 'Везучий чёрт',
    'Proud Parent': 'Гордый родитель',
    'Got Married': 'Свадьба',
    'Tournament Champion': 'Чемпион турнира',
    'Battle Royale Champion': 'Чемпион королевской битвы',
    'Master of Champions': 'Мастер чемпионов',
    'Beat Tough Thief': 'Побит крутой вор',
    'Enemy Reformed': 'Исправившийся враг',
    "Beggar's Friend": 'Друг нищего',
    'Gambler Beaten': 'Побит азартный игрок',
    'Weird Item': 'Странный предмет',
    "Drunkard's Friend": 'Друг пьяницы',
    'Fat Girl Defeated': 'Побита толстая девушка',
    'Personality Change': 'Смена личности',
    'Lone Warrior': 'Одинокий воин',
    'Against All Odds': 'Вопреки всему',
    'Narrow Victory': 'Трудная победа',
    'Split-Second Victory': 'Победа в последний миг',
    'Quick Victory': 'Быстрая победа',
    'Weak Short Punch': 'Слабый короткий удар кулаком',
    'Weapons Competence': 'Владение оружием',
    'Whirlwind Kicks': 'Вихревые удары ногами',
    'Wino Form': 'Форма пьяницы',
    'Wooden Limbs': 'Деревянные конечности',
    # -- style/tech single words (style-gen vocabulary as standalone names) --
    'Acrobatic': 'Акробатический',
    'Air': 'Воздушный',
    'Astral': 'Астральный',
    'Attacking': 'Атакующий',
    'Avalanche': 'Лавинный',
    'Averting': 'Уклончивый',
    'Balanced': 'Уравновешенный',
    'Bizarre': 'Причудливый',
    'Burning': 'Пылающий',
    'Cautious': 'Осторожный',
    'Clinging': 'Цепкий',
    'Dancing': 'Танцующий',
    'Defending': 'Защитный',
    'Drunken': 'Пьяный',
    'Earth': 'Земляной',
    'Elusive': 'Неуловимый',
    'Emerald': 'Изумрудный',
    'Exotic': 'Экзотический',
    'Fire': 'Огненный',
    'Flying': 'Летающий',
    'Formless': 'Бесформенный',
    'Furious': 'Яростный',
    'Grappling': 'Борцовский',
    'Guarding': 'Сторожевой',
    'Heavenly': 'Небесный',
    'Ice': 'Ледяной',
    'Indestructible': 'Несокрушимый',
    'Invulnerable': 'Неуязвимый',
    'Iron': 'Железный',
    'Kicking': 'Ножной',
    'Light-Footed': 'Легконогий',
    'Long-Range': 'Дальнобойный',
    'Meteor': 'Метеорный',
    'Mid-Range': 'Среднедистанционный',
    'Misty': 'Туманный',
    'Moon': 'Лунный',
    'Mystic': 'Мистический',
    'Nimble': 'Проворный',
    'Northern': 'Северный',
    'Obsidian': 'Обсидиановый',
    'Open-Handed': 'Ладонный',
    'Paralyzing': 'Парализующий',
    'Persevering': 'Упорный',
    'Powerful': 'Мощный',
    'Punching': 'Кулачный',
    'Quick': 'Скорый',
    'Rainbow': 'Радужный',
    'Razor': 'Бритвенный',
    'Red': 'Красный',
    'Retaliating': 'Ответный',
    'Rising': 'Восходящий',
    'Sharp': 'Острый',
    'Shattering': 'Сокрушительный',
    'Slashing': 'Рубящий',
    'Snow': 'Снежный',
    'Spiky': 'Колючий',
    'Stone': 'Каменный',
    'Storm': 'Грозовой',
    'Strong': 'Сильный',
    'Sun': 'Солнечный',
    'Swift-Striking': 'Молниеносный',
    'Tipsy': 'Подвыпивший',
    'Tough': 'Крепкий',
    'Unstoppable': 'Неостановимый',
    'Vengeful': 'Мстительный',
    'Venom': 'Ядовитый',
    'Vigorous': 'Энергичный',
    'Water': 'Водяной',
    'White': 'Белый',
    'Wind': 'Ветреный',
    'Wooden': 'Деревянный',
    'Wino': 'Пьяница',
    # -- animal nouns (style-gen W3 as standalone names) --
    'Bear': 'Медведь',
    'Boar': 'Кабан',
    'Butterfly': 'Бабочка',
    'Cat': 'Кот',
    'Cobra': 'Кобра',
    'Crab': 'Краб',
    'Crane': 'Журавль',
    'Eagle': 'Орёл',
    'Elephant': 'Слон',
    'Falcon': 'Сокол',
    'Fox': 'Лиса',
    'Hawk': 'Ястреб',
    'Lion': 'Лев',
    'Lizard': 'Ящерица',
    'Mantis': 'Богомол',
    'Ox': 'Бык',
    'Panther': 'Пантера',
    'Phoenix': 'Феникс',
    'Rat': 'Крыса',
    'Shark': 'Акула',
    'Squirrel': 'Белка',
    'Turtle': 'Черепаха',
    'Viper': 'Гадюка',
    'Wolf': 'Волк',
    # -- techniques --
    'Acrobatic Training': 'Акробатическая подготовка',
    'Acrobatics': 'Акробатика',
    'Air Attacks': 'Воздушные атаки',
    'Anything Is a Weapon': 'Всё — оружие',
    'Astral Footwork': 'Астральная работа ног',
    'Attack Is Defense': 'Атака — это защита',
    'Attack Method': 'Метод атаки',
    'Attacking Cobra': 'Атакующая кобра',
    'Attacking Wolf': 'Атакующий волк',
    'Avert Attacks': 'Отвод атак',
    "Bear's Strength": 'Сила медведя',
    'Behind You': 'Позади тебя',
    'Behind You All': 'Позади всех вас',
    'Blood Strikes': 'Кровавые удары',
    "Brawler's Resilience": 'Стойкость задиры',
    'Burning Fury': 'Пылающая ярость',
    'Butterfly Swords': 'Мечи-бабочки',
    "Cat's Attacking Distance": 'Атакующая дистанция кота',
    'Cautious Attacks': 'Осторожные атаки',
    'Cornered Rat': 'Загнанная в угол крыса',
    'Countless Palms': 'Бесчисленные ладони',
    'Crane Flapping Wings': 'Журавль машет крыльями',
    'Crippling Strikes': 'Калечащие удары',
    'Dance-Like Form': 'Танцевальная форма',
    'Deadly Venom': 'Смертельный яд',
    'Defending Crab': 'Обороняющийся краб',
    'Defense Stance': 'Защитная стойка',
    'Dragon Guards a Treasure': 'Дракон стережёт сокровище',
    'Drunken Moves': 'Пьяные движения',
    "Earth's Orbit": 'Орбита Земли',
    "Elephant's Health": 'Здоровье слона',
    'Elusive Moves': 'Неуловимые движения',
    'Emerald Flow': 'Изумрудный поток',
    "Emperor's Fortress": 'Крепость императора',
    'Emphasis on Speed': 'Упор на скорость',
    'Enraged Mantis': 'Разъярённый богомол',
    'Environment Domination': 'Господство над окружением',
    'Environment Fighting': 'Бой с использованием окружения',
    'Exotic Boxing': 'Экзотический бокс',
    'Exotic Strikes Training': 'Тренировка экзотических ударов',
    'Explosive Strikes': 'Взрывные удары',
    'Falling Meteorites': 'Падающие метеориты',
    'Fast Movement': 'Быстрое передвижение',
    'Fierce Strikes': 'Свирепые удары',
    'Fist of Fury': 'Кулак ярости',
    'Fist of Fury II': 'Кулак ярости II',
    'Fist Training': 'Тренировка кулака',
    'Fluttering Butterfly': 'Порхающая бабочка',
    'Flying Eagle': 'Летящий орёл',
    'Flying Monkey and Golden Fox': 'Летящая обезьяна и золотая лиса',
    'Focus': 'Фокус',
    'Fox Strikes Back': 'Лиса бьёт в ответ',
    'Golden Lotus Stance': 'Стойка золотого лотоса',
    'Grappling Training': 'Борцовская подготовка',
    'Guard Form': 'Защитная форма',
    'Guard While Striking': 'Защита во время удара',
    'Hard like Ice': 'Твёрдый как лёд',
    'Hardened Palms': 'Закалённые ладони',
    'Healing Water': 'Целебная вода',
    'Health Breathing': 'Оздоровительное дыхание',
    'Heavenly Hands': 'Небесные руки',
    "Hero's Resilience": 'Стойкость героя',
    'Horse-like Stamina': 'Лошадиная выносливость',
    'Hunting Falcon': 'Охотящийся сокол',
    'Hunting Hawk': 'Охотящийся ястреб',
    'Hunting Leopard': 'Охотящийся леопард',
    'Hurricane Legs': 'Ураганные ноги',
    'Indestructible Body': 'Несокрушимое тело',
    'Inferno': 'Инферно',
    'Iron Skin': 'Железная кожа',
    'Iron Vest': 'Железный жилет',
    'Jump Technique': 'Прыжковая техника',
    'Kick Training': 'Тренировка ударов ногами',
    'Kung-Fu Fury': 'Ярость кунг-фу',
    'Light Feet': 'Лёгкие ноги',
    'Lightning Spear': 'Молниеносное копьё',
    'Lightning-Fast Movement': 'Молниеносное передвижение',
    'Lightning-Fast Strikes': 'Молниеносные удары',
    "Lion's Paws": 'Лапы льва',
    'Long-Range Fighting': 'Бой на дальней дистанции',
    'Lotus Stance': 'Стойка лотоса',
    'Meteor Punches': 'Метеорные удары кулаками',
    'Mid-Range Fighting': 'Бой на средней дистанции',
    'Misty Steps': 'Туманные шаги',
    'Monkey and Fox': 'Обезьяна и лиса',
    "Moon's Orbit": 'Орбита Луны',
    'Nimble Movements': 'Проворные движения',
    'Northern Style Kung-fu': 'Кунг-фу северного стиля',
    "Ox's Stamina": 'Выносливость быка',
    'Palm and Claw Training': 'Тренировка ладони и когтя',
    'Palms of Justice': 'Ладони справедливости',
    'Panther Attacks': 'Атаки пантеры',
    'Perseverance': 'Упорство',
    'Playing Monkey': 'Играющая обезьяна',
    'Powerful Kicks': 'Мощные удары ногами',
    'Preemptive Strikes': 'Упреждающие удары',
    'Rainbow Steps': 'Радужные шаги',
    'Razor-Sharp Strikes': 'Бритвенно-острые удары',
    'Regenerating Lizard': 'Регенерирующая ящерица',
    'Relentless Storm': 'Неумолимый шторм',
    'Retaliation': 'Возмездие',
    'Retaliative Blows': 'Ответные удары',
    'Rising from the Ashes': 'Восставший из пепла',
    'Rising Phoenix': 'Восходящий феникс',
    'Rusher Boar': 'Таранящий кабан',
    'Shadow of a Shadow': 'Тень тени',
    'Shadow Slips Away': 'Тень ускользает',
    'Shark Pursues Its Prey': 'Акула преследует добычу',
    'Sky Dragon': 'Небесный дракон',
    'Sky Saber': 'Небесная сабля',
    'Snowfall': 'Снегопад',
    'Spiky Attacks': 'Колючие атаки',
    "Squirrel's Agility": 'Ловкость белки',
    'Star Sword': 'Звёздный меч',
    'Stinging Scorpion': 'Жалящий скорпион',
    'Stinging Viper': 'Жалящая гадюка',
    'Stone Forearms': 'Каменные предплечья',
    'Strange But Deadly': 'Странный, но смертоносный',
    'Strength Training': 'Силовая тренировка',
    'Strikes of Vengeance': 'Удары возмездия',
    'Strong as an Ox': 'Сильный как бык',
    "Sun's Orbit": 'Орбита Солнца',
    'Superior Iron Vest': 'Превосходный железный жилет',
    'Thunder Staff': 'Громовой посох',
    "Tiger's Rage": 'Ярость тигра',
    "Toad's Toughness": 'Крепость жабы',
    'Toughness': 'Крепость',
    "Turtle's Shell": 'Панцирь черепахи',
    'Twisting Snake': 'Извивающаяся змея',
    'Unlikely Weapons': 'Неожиданное оружие',
    'Unstoppable Attacks': 'Неостановимые атаки',
    'Vengeful Fox': 'Мстительная лиса',
    'Vigor': 'Живость',
    'Vitality Breathing': 'Дыхание жизненной силы',
    'Wall-like Protection': 'Защита как стена',
    # -- style techs with roman numerals --
    'Bagua Zhang I': 'Багуа Чжан I',
    'Bagua Zhang II': 'Багуа Чжан II',
    'Bagua Zhang III': 'Багуа Чжан III',
    'Capoeira I': 'Капоэйра I',
    'Capoeira II': 'Капоэйра II',
    'Capoeira III': 'Капоэйра III',
    'Centipede I': 'Многоножка I',
    'Centipede II': 'Многоножка II',
    'Choy Li Fut I': 'Чой Ли Фут I',
    'Choy Li Fut II': 'Чой Ли Фут II',
    'Choy Li Fut III': 'Чой Ли Фут III',
    'Cowabunga I': 'Ковабанга I',
    'Cowabunga II': 'Ковабанга II',
    'Cowabunga III': 'Ковабанга III',
    'Dragon I': 'Дракон I',
    'Dragon II': 'Дракон II',
    'Dragon III': 'Дракон III',
    'Drunken Boxing I': 'Пьяный бокс I',
    'Drunken Boxing II': 'Пьяный бокс II',
    'Drunken Boxing III': 'Пьяный бокс III',
    'Drunken Dragon I': 'Пьяный дракон I',
    'Drunken Dragon II': 'Пьяный дракон II',
    'Drunken Dragon III': 'Пьяный дракон III',
    'Eagle Claw I': 'Коготь орла I',
    'Eagle Claw II': 'Коготь орла II',
    'Eagle Claw III': 'Коготь орла III',
    'Eight Extremities Fist I': 'Кулак восьми пределов I',
    'Eight Extremities Fist II': 'Кулак восьми пределов II',
    'Eight Extremities Fist III': 'Кулак восьми пределов III',
    'English Boxing I': 'Английский бокс I',
    'English Boxing II': 'Английский бокс II',
    'English Boxing III': 'Английский бокс III',
    'Gecko I': 'Геккон I',
    'Gecko II': 'Геккон II',
    'Gecko III': 'Геккон III',
    'Hung Ga I': 'Хун Гар I',
    'Hung Ga II': 'Хун Гар II',
    'Hung Ga III': 'Хун Гар III',
    'Karate I': 'Карате I',
    'Karate II': 'Карате II',
    'Karate III': 'Карате III',
    'Leopard I': 'Леопард I',
    'Leopard II': 'Леопард II',
    'Leopard III': 'Леопард III',
    'Monkey I': 'Обезьяна I',
    'Monkey II': 'Обезьяна II',
    'Monkey III': 'Обезьяна III',
    'Muai Thai I': 'Муай-тай I',
    'Muai Thai II': 'Муай-тай II',
    'Muai Thai III': 'Муай-тай III',
    'Poking Foot I': 'Тычковая нога I',
    'Poking Foot II': 'Тычковая нога II',
    'Praying Mantis I': 'Богомол I',
    'Praying Mantis II': 'Богомол II',
    'Praying Mantis III': 'Богомол III',
    'Scorpion I': 'Скорпион I',
    'Scorpion II': 'Скорпион II',
    'Scorpion III': 'Скорпион III',
    'Shaolin Fist I': 'Шаолиньский кулак I',
    'Shaolin Fist II': 'Шаолиньский кулак II',
    'Shaolin Fist III': 'Шаолиньский кулак III',
    'Snake I': 'Змея I',
    'Snake II': 'Змея II',
    'Snake III': 'Змея III',
    'Taekwondo I': 'Тхэквондо I',
    'Taekwondo II': 'Тхэквондо II',
    'Taekwondo III': 'Тхэквондо III',
    'Taiji I': 'Тайцзи I',
    'Taiji II': 'Тайцзи II',
    'Taiji III': 'Тайцзи III',
    "Thief's Shadow I": 'Тень вора I',
    "Thief's Shadow II": 'Тень вора II',
    "Thief's Shadow III": 'Тень вора III',
    'Tiger I': 'Тигр I',
    'Tiger II': 'Тигр II',
    'Tiger III': 'Тигр III',
    'Toad I': 'Жаба I',
    'Toad II': 'Жаба II',
    'Toad III': 'Жаба III',
    'White Crane I': 'Белый журавль I',
    'White Crane II': 'Белый журавль II',
    'White Crane III': 'Белый журавль III',
    'Wing Chun I': 'Вин Чун I',
    'Wing Chun II': 'Вин Чун II',
    'Wing Chun III': 'Вин Чун III',
    'Wrestling I': 'Борьба I',
    'Wrestling II': 'Борьба II',
    'Wrestling III': 'Борьба III',
    'Xing Yi I': 'Синъи I',
    'Xing Yi II': 'Синъи II',
    'Xing Yi III': 'Синъи III',
    # -- special moves --
    'Cannon Fist': 'Пушечный кулак',
    'Dragon Claw': 'Коготь дракона',
    'Finishing Kick': 'Добивающий удар ногой',
    'Finishing Punch': 'Добивающий удар кулаком',
    'Leap Back': 'Прыжок назад',
    'Leap Forward': 'Прыжок вперёд',
    'Leopard Punch': 'Леопардовый удар кулаком',
    'Mantis Hook': 'Крюк богомола',
    'No-Shadow Kick': 'Бестеневой удар ногой',
    'Rush Forward': 'Рывок вперёд',
    'Step Back': 'Шаг назад',
    'Step Forward': 'Шаг вперёд',
    # -- robber nicknames & misc --
    'Atrocious': 'Чудовищный',
    'Bloody': 'Кровавый',
    'Cruel': 'Жестокий',
    'Evil': 'Злой',
    'Fat': 'Толстый',
    'Greedy': 'Жадный',
    'Horrible': 'Ужасный',
    'Immortal': 'Бессмертный',
    'Jerky': 'Дёрганый',
    'Killer': 'Убийца',
    'Little': 'Маленький',
    'Mad': 'Безумный',
    'Nasty': 'Гадкий',
    'Opium': 'Опиум',
    'Ruthless': 'Безжалостный',
    'Unbeatable': 'Непобедимый',
    'Vicious': 'Злобный',
    'Wild': 'Дикий',
    # -- special moves & forms --
    '18 Attack Forms': '18 атакующих форм',
    '18 Defense Forms': '18 защитных форм',
    '36 Attack Forms': '36 атакующих форм',
    '36 Defense Forms': '36 защитных форм',
    'A Hundred Arms': 'Сто рук',
    'Catch Breath': 'Перевести дыхание',
    'Do Nothing': 'Ничего не делать',
    'Guard': 'Защита',
    'Forward Step': 'Шаг вперёд',
    'Retreat': 'Отступление',
    'Punch': 'Удар кулаком',
    'Kick': 'Удар ногой',
    'Throw': 'Бросок',
    'Sweep': 'Подсечка',
    'Trip': 'Подножка',
    'Dodge': 'Уклонение',
    'Run Away': 'Бегство',
    'Shove': 'Толчок',
    'Backfist': 'Удар тыльной стороной кулака',
}
