# Russian translations for the kfw prose domain (milestone 1 vertical slice).
# Filled into locale/ru/LC_MESSAGES/kfw.po by fill_prose_ru.py.
# Keys must match msgids exactly, including leading spaces/newlines.
TR = {
    '\nAuto fight?': '\nАвтобой?',
    ' (boring...)': ' (скучновато...)',
    ' (epic!)': ' (эпично!)',
    ' (guarding while attacking)': ' (защищается в атаке)',
    ' *FURY*': ' *ЯРОСТЬ*',
    ' agility-based {dmg} ({hp})': ' {dmg} (от ловкости) ({hp})',
    ' falls to the ground! {dmg} ({hp})': ' падает на землю! {dmg} ({hp})',
    ' gasps for breath!': ' задыхается!',
    ' KNOCK-OUT!': ' НОКАУТ!',
    ' knocked back {dist} step!': ' отлетает на {dist} шаг назад!',
    ' level-based {dmg} ({hp})': ' {dmg} (от уровня) ({hp})',
    ' off-balance!': ' теряет равновесие!',
    ' qi-based {dmg} ({hp})': ' {dmg} (от ци) ({hp})',
    ' shocked!': ' в шоке!',
    ' slowed down!': ' замедляется!',
    ' speed-based {dmg} ({hp})': ' {dmg} (от скорости) ({hp})',
    ' strength-based {dmg} ({hp})': ' {dmg} (от силы) ({hp})',
    ' stunned!': ' в ступоре!',
    '*LEVEL UP*': '*НОВЫЙ УРОВЕНЬ*',
    '+COUNTER!+': '+КОНТРАТАКА!+',
    ", 'b' to go back": ", 'b' — назад",
    '--- Group {n} (your group) ---': '--- Группа {n} (ваша) ---',
    '--- Group {n} ---': '--- Группа {n} ---',
    '-{dam} HP': '-{dam} HP',
    '<-PREEMPTIVE!-<': '<-УПРЕЖДЕНИЕ!-<',
    '[bold]Free for all![/bold]': '[bold]Каждый сам за себя![/bold]',
    '[bold]Group free for all![/bold]': '[bold]Групповая свалка![/bold]',
    '(Press any key)': '(Нажмите любую клавишу)',
    'Acc': 'Точн',
    'Accomplishments': 'Достижения',
    'acrob.str': 'акроб.уд.',
    'acrobatic strike efficiency': 'эффективность акробатических ударов',
    'Agi': 'Лов',
    'Agility': 'Ловкость',
    'agility': 'ловкость',
    'Are these styles ok?': 'Эти стили подходят?',
    'As {name} trains hard, delving deeper into the art of {style}, he '
    'discovers a way to improve one of the style\'s techniques...':
        'Усердно тренируясь и постигая всё более глубокие тайны стиля {style}, '
        '{name} открывает способ улучшить одну из техник стиля...',
    'attack': 'атака',
    'Auto save?': 'Автосохранение?',
    'Back': 'Назад',
    'barely': 'едва ',
    'bleeding': 'кровотечение',
    'block efficiency': 'эффективность блока',
    'blocks': 'блоки',
    'cause bleeding': 'вызов кровотечения',
    'chance to resist KO': 'шанс устоять при нокауте',
    'chance to use environment': 'шанс использовать окружение',
    'Choose a move to learn:': 'Выберите приём для изучения:',
    'Choose a style': 'Выберите стиль',
    'Choose a technique to improve:': 'Выберите технику для улучшения:',
    'Choose a technique to learn:': 'Выберите технику для изучения:',
    'Choose target:': 'Выберите цель:',
    'close-range': 'ближняя дистанция',
    'close-range strike efficiency': 'эффективность ударов вблизи',
    'Cmpl': 'Слож',
    'Co-op mode?': 'Кооперативный режим?',
    'counterattack chance': 'шанс контратаки',
    'counters': 'контратаки',
    'Crash Course (faster level progression)': 'Ускоренный курс (быстрая прокачка)',
    'Crime rate?': 'Уровень преступности?',
    'critical attack chance': 'шанс критической атаки',
    'critical attack power': 'сила критической атаки',
    'CRITICAL!': 'КРИТИЧЕСКИЙ УДАР!',
    'criticals': 'критические удары',
    'Customize game settings? (choose "no" to keep the defaults)':
        'Настроить параметры игры? (ответьте "нет", чтобы оставить умолчания)',
    'dam.reduc.': 'сниж.урона',
    'damage is reduced!': 'урон снижен!',
    'damage reduction': 'снижение урона',
    'Debug Menu': 'Меню отладки',
    'defense': 'защита',
    'defense penalty (20% by default)': 'штраф защиты (по умолчанию 20%)',
    'defense while lying': 'защита лёжа',
    'disarm': 'обезоруживание',
    'disarm chance when attacking': 'шанс обезоружить в атаке',
    'disarm chance when defending': 'шанс обезоружить в защите',
    'disarms': 'обезоруживает',
    'Dist': 'Дист',
    'Do you want to see what AI players do?': 'Хотите видеть действия ИИ-игроков?',
    'dodge': 'уклонение',
    'dodge efficiency': 'эффективность уклонения',
    'Draw!': 'Ничья!',
    'drun.str.': 'пьян.уд.',
    'drunken strike efficiency': 'эффективность пьяных ударов',
    'easily': 'легко ',
    'elbow strike efficiency': 'эффективность ударов локтем',
    'elbows': 'локти',
    'environment': 'окружение',
    'Fail!': 'Неудача!',
    'fall damage': 'урон от падения',
    'Farewell, brave warrior!': 'Прощай, храбрый воин!',
    'Finish Game': 'Завершить игру',
    'Full co-op': 'Полный кооператив',
    'Func': 'Функ',
    'fury': 'ярость',
    'fury chance': 'шанс ярости',
    'Gang-Ridden (high crime)': 'Город банд (высокая преступность)',
    'Getting By (default poverty)': 'Перебиваемся (обычная бедность)',
    'grab chance': 'шанс захвата',
    'grabs': 'захваты',
    'grabs an improvised weapon!': 'хватает подручное оружие!',
    'grappling': 'борьба',
    'grappling efficiency': 'эффективность борьбы',
    'guard': 'защитная стойка',
    'guard efficiency': 'эффективность защитной стойки',
    'guard while atk': 'защита в атаке',
    'guard while attacking': 'защита во время атаки',
    'Hard Times (high poverty)': 'Тяжёлые времена (высокая бедность)',
    'Health': 'Здоровье',
    'health': 'здоровье',
    'hit: {dmg} ({hp})': 'попадание: {dmg} ({hp})',
    'Hlt': 'Здр',
    'HP': 'HP',
    'HP gain': 'восстановление HP',
    'HP gain per turn': 'HP за ход',
    'HP:{}': 'HP:{}',
    'improv.weapons': 'подруч.оружие',
    'Improve:': 'Улучшить:',
    'in-fight improvised weapon chance': 'шанс подручного оружия в бою',
    'Input file name: ': 'Введите имя файла: ',
    'INSTANT KNOCK-OUT!!!': 'МГНОВЕННЫЙ НОКАУТ!!!',
    'invalid input, try again': 'неверный ввод, попробуйте ещё раз',
    'is BLEEDING!': 'ИСТЕКАЕТ КРОВЬЮ!',
    'is in FURY!': 'в ЯРОСТИ!',
    'Is this character ok?': 'Этот персонаж подходит?',
    'Items': 'Предметы',
    'jumping strike efficiency': 'эффективность ударов в прыжке',
    'jumps': 'прыжки',
    'Keep playing indefinitely?': 'Продолжать играть бессрочно?',
    'kick efficiency': 'эффективность пинков',
    'kicks': 'пинки',
    'knee strike efficiency': 'эффективность ударов коленом',
    'knees': 'колени',
    'Kung-Fu Backwater (low enthusiasm)': 'Кунг-фу глухомань (слабый энтузиазм)',
    'Kung-Fu Craze (high enthusiasm)': 'Кунг-фу лихорадка (сильный энтузиазм)',
    'Kung-fu enthusiasm?': 'Энтузиазм к кунг-фу?',
    'LEV': 'УР',
    'Level progression?': 'Скорость прокачки?',
    'Load': 'Загрузить',
    'long-range': 'дальняя дистанция',
    'long-range strike efficiency': 'эффективность ударов издалека',
    'low fall dam': 'малый урон от падения',
    'lv.{}': 'ур.{}',
    'lying dfs': 'защита лёжа',
    'Man': 'Мужчина',
    'maneuv.time': 'время манёвра',
    'maneuver time cost': 'стоимость манёвра по времени',
    'Martial Town (default enthusiasm)': 'Город единоборств (обычный энтузиазм)',
    'max QP': 'макс. QP',
    'max stamina': 'макс. выносливость',
    'mid-range': 'средняя дистанция',
    'mid-range strike efficiency': 'эффективность ударов со средней дистанции',
    'Miss!': 'Промах!',
    'Move': 'Приём',
    'move complexity': 'сложность приёмов',
    'move cplx.': 'сложн. приёмов',
    'Moves': 'Приёмы',
    'Multi-knockout': 'Мультинокаут',
    'NAME': 'ИМЯ',
    'Next page': 'След. страница',
    'no': 'нет',
    'No co-op': 'Без кооператива',
    'No stats recorded.': 'Статистика не записана.',
    'Not a scratch': 'Ни царапины',
    'Number of players?': 'Количество игроков?',
    'off-bal.atk': 'дисб.атк',
    'off-bal.dfs': 'дисб.зщт',
    'off-balance attack': 'атака при потере равновесия',
    'off-balance defense': 'защита при потере равновесия',
    'palm str.': 'ладонь',
    'palm strike efficiency': 'эффективность ударов ладонью',
    'passes out because of bleeding!': 'теряет сознание от кровопотери!',
    'Peaceful Town (low crime)': 'Мирный город (низкая преступность)',
    'Play as a man or a woman?': 'Играть за мужчину или женщину?',
    'Player {n} -- human player?': 'Игрок {n} — человек?',
    'Poverty?': 'Бедность?',
    'preemptive': 'упреждение',
    'preemptive strike chance': 'шанс упреждающего удара',
    'Press Enter': 'Нажмите Enter',
    'Press Enter to see stats.': 'Нажмите Enter, чтобы увидеть статистику.',
    'Previous page': 'Пред. страница',
    'Prosperous (low poverty)': 'Благополучный (низкая бедность)',
    'punch efficiency': 'эффективность ударов кулаком',
    'punches': 'удары кулаком',
    'Pwr': 'Мощь',
    'Qi': 'Ци',
    'qi': 'ци',
    'qi when attacking': 'ци при атаке',
    'qi/atk': 'ци/атака',
    'QP': 'QP',
    'QP to start with': 'начальное QP',
    'QP/turn': 'QP/ход',
    'QP:{}': 'QP:{}',
    'Quick victory': 'Быстрая победа',
    'Quit': 'Выход',
    'Randomly generated styles?': 'Случайно сгенерированные стили?',
    'resist KO': 'сопротивление нокауту',
    'resists being knocked out!': 'удерживается на ногах!',
    'restore stamina': 'восстановление выносливости',
    'Rough Edges (default crime)': 'Неспокойный район (обычная преступность)',
    'Save': 'Сохранить',
    'Save and Quit': 'Сохранить и выйти',
    'Save slideshow': 'Сохранить слайд-шоу',
    'Saved successfully.': 'Сохранено успешно.',
    'Slideshow ({n})': 'Слайд-шоу ({n})',
    'SP': 'SP',
    'SP:{}': 'SP:{}',
    'Spd': 'Скр',
    'Speed': 'Скорость',
    'speed': 'скорость',
    'Sta': 'Вын',
    'stamina': 'выносливость',
    'Stats': 'Статистика',
    'Str': 'Сил',
    'Strength': 'Сила',
    'strength': 'сила',
    'strike time': 'время удара',
    'strike time cost': 'стоимость удара по времени',
    'Students': 'Ученики',
    'stun': 'оглушение',
    'stun chance': 'шанс оглушения',
    'STYLE': 'СТИЛЬ',
    'Techniques': 'Техники',
    'Techniques:': 'Техники:',
    'The All-Schools Tournament will be held at the end of the month.':
        'Турнир всех школ состоится в конце месяца.',
    'The Classic Path (default progression)': 'Классический путь (обычная прокачка)',
    'The fight lasted {t}': 'Бой длился {t}',
    'The Long Road (slower level progression)': 'Долгий путь (медленная прокачка)',
    'Through countless hours of training, {name} finally grasps the deepest '
    'secret of {style} — {tech}.':
        'После бесчисленных часов тренировок {name} наконец постигает '
        'глубочайшую тайну стиля {style} — {tech}.',
    'Tier': 'Ранг',
    'Time': 'Время',
    'Timeline': 'Хронология',
    'unblock.': 'неблок.',
    'unblockable attack': 'неблокируемая атака',
    'UNBLOCKABLE!': 'НЕБЛОКИРУЕМЫЙ!',
    'uses the environment!': 'использует окружение!',
    'vs crowd': 'против толпы',
    'WEAPON': 'ОРУЖИЕ',
    'weapon efficiency': 'эффективность оружия',
    'weapons': 'оружие',
    'Woman': 'Женщина',
    'yes': 'да',
    '{group} win.': '{group} побеждают.',
    '{min} min. {sec} sec.': '{min} мин. {sec} сек.',
    '{n1} {verb} {n2} while attacking': '{n1} {verb} {n2} в атаке',
    '{n1} {verb} {n2} while blocking': '{n1} {verb} {n2} в блоке',
    '{n1}: {move} @ {n2}': '{n1}: {move} @ {n2}',
    '{n1}{fury}: {move} @ {n2}': '{n1}{fury}: {move} @ {n2}',
    '{name} ({style})': '{name} ({style})',
    '{name} becomes {victory}!': '{name} получает титул: {victory}!',
    '{name} is now number {rank} at his school.':
        '{name} теперь номер {rank} в своей школе.',
    '{name} learns {tech} ({descr}).': '{name} изучает: {tech} ({descr}).',
    '{name} wins.': '{name} побеждает.',
    '{name} {adv}blocks! ({pwr})': '{name} {adv}блокирует! ({pwr})',
    '{name} {adv}dodges!': '{name} {adv}уклоняется!',
    '{name} {msg}': '{name} {msg}',
    '{name}: "{q}"': '{name}: "{q}"',
    '{name}: *LEVEL UP*': '{name}: *НОВЫЙ УРОВЕНЬ*',
    '{name}: strikes {landed}/{thrown} landed ({accuracy}), damage dealt {dam}, '
    'criticals {crits}, epics {epics}, moves: {moves}':
        '{name}: удары {landed}/{thrown} попали ({accuracy}), нанесено урона '
        '{dam}, критических {crits}, эпичных {epics}, приёмы: {moves}',
    '{name}: {bonus}': '{name}: {bonus}',
    '{name}: {move}': '{name}: {move}',
    '{sec} sec.': '{sec} сек.',
    '~*~*~EPIC!!!~*~*~': '~*~*~ЭПИЧНО!!!~*~*~',
    '{name} is practicing in the school\'s courtyard when {master} calls him '
    'to the main hall.\n{master}: "{name}, you have been most diligent. Few '
    'students go as far as you have, so today I can trust you with the inner '
    'teaching of our school. The style the outside world knows as '
    '{public_style} has a true name, whispered only to the most trusted '
    'disciples: {style}! And with it comes the secret technique — {tech}. '
    'Guard this knowledge, and never speak of it outside these walls."':
        '{name} тренируется во дворе школы, когда {master} зовёт в главный '
        'зал.\n{master}: "{name}, ты был очень прилежен. Немногие ученики '
        'заходят так далеко, как ты, поэтому сегодня я могу доверить тебе '
        'внутреннее учение нашей школы. У стиля, который внешний мир знает '
        'как {public_style}, есть истинное имя, которое шепотом передают '
        'лишь самым доверенным ученикам: {style}! А вместе с ним — секретная '
        'техника: {tech}. Береги это знание и не говори о нём никому за '
        'этими стенами."',
    '{name} is practicing in the school\'s courtyard when {master} calls him '
    'to the main hall.\n{master}: "{name}, you have been most diligent. Few '
    'students go as far as you have. It is time you learned the secret '
    'technique of {style} — {tech}. Guard this knowledge, and never speak of '
    'it outside these walls."':
        '{name} тренируется во дворе школы, когда {master} зовёт в главный '
        'зал.\n{master}: "{name}, ты был очень прилежен. Немногие ученики '
        'заходят так далеко, как ты. Пришло время узнать секретную технику '
        'стиля {style} — {tech}. Береги это знание и не говори о нём никому '
        'за этими стенами."',
}

# plural entries: msgid -> (msgstr[0], msgstr[1], msgstr[2])
TR_PLURAL = {
    ' knocked back {dist} step!': (
        ' отлетает на {dist} шаг назад!',
        ' отлетает на {dist} шага назад!',
        ' отлетает на {dist} шагов назад!',
    ),
}
