DFLT_TOURN_PART_NAME = 'Unknown'
GANG_LEADER = 'Gang Leader'

GROUP_NAMES = {'Thug 1': 'Thugs', 'Robber 1': 'Robbers'}

SURNAME_PARTS = [
    'bai',
    'cai',
    'cao',
    'chang',
    'chen',
    'cheng',
    'cui',
    'dai',
    'deng',
    'ding',
    'dong',
    'du',
    'duan',
    'fan',
    'fang',
    'feng',
    'fu',
    'gao',
    'gong',
    'gu',
    'guo',
    'han',
    'hao',
    'he',
    'hou',
    'hu',
    'huang',
    'jen',
    'jia',
    'jiang',
    'jin',
    'kang',
    'kong',
    'lai',
    'lei',
    'li',
    'liang',
    'liao',
    'lin',
    'liu',
    'long',
    'lu',
    'luo',
    'ma',
    'mao',
    'meng',
    'mo',
    'pan',
    'peng',
    'qian',
    'qiao',
    'qin',
    'qiu',
    'shao',
    'shen',
    'shi',
    'song',
    'su',
    'sun',
    'tan',
    'tang',
    'tao',
    'tian',
    'wan',
    'wang',
    'wei',
    'wen',
    'wu',
    'xia',
    'xiang',
    'xiao',
    'xie',
    'xiong',
    'xu',
    'xue',
    'yan',
    'yang',
    'yao',
    'ye',
    'yi',
    'yin',
    'yu',
    'yuan',
    'zeng',
    'zhang',
    'zhao',
    'zheng',
    'zhong',
    'zhou',
    'zhu',
    'zou',
]

FIRST_NAME_PARTS = [
    'bai',
    'cai',
    'cao',
    'chang',
    'chao',
    'chen',
    'cheng',
    'chu',
    'cui',
    'dai',
    'deng',
    'ding',
    'dong',
    'du',
    'duan',
    'fan',
    'fang',
    'fei',
    'feng',
    'fu',
    'gang',
    'gao',
    'gong',
    'gu',
    'gui',
    'guo',
    'han',
    'hao',
    'he',
    'hou',
    'hu',
    'huang',
    'hung',
    'jen',
    'jia',
    'jiang',
    'jie',
    'jin',
    'jing',
    'jiu',
    'juan',
    'jun',
    'kang',
    'kong',
    'lai',
    'lan',
    'lei',
    'li',
    'liang',
    'liao',
    'lin',
    'liu',
    'long',
    'lu',
    'luo',
    'ma',
    'mao',
    'meng',
    'min',
    'ming',
    'mo',
    'na',
    'pan',
    'peng',
    'ping',
    'qian',
    'qiang',
    'qiao',
    'qin',
    'qiu',
    'shao',
    'shen',
    'sheng',
    'shi',
    'shing',
    'song',
    'su',
    'sun',
    'tan',
    'tang',
    'tao',
    'tian',
    'to',
    'wan',
    'wang',
    'wei',
    'wen',
    'wu',
    'xi',
    'xia',
    'xiang',
    'xiao',
    'xie',
    'xiong',
    'xiu',
    'xu',
    'xue',
    'yan',
    'yang',
    'yao',
    'ye',
    'yi',
    'yin',
    'ying',
    'yong',
    'yu',
    'yuan',
    'zeng',
    'zhang',
    'zhao',
    'zheng',
    'zhong',
    'zhou',
    'zhu',
    'ziu',
    'zou',
]

FOREIGN_COUNTRIES = 'England Germany Japan Korea Thailand Brazil'.split()
FOREIGN_NAMES = {
    'England': 'Smith Jones Taylor Brown Williams Wilson \
                            Johnson Walker Robinson Green Roberts'.split(),
    'Germany': 'Muller Schmidt Schneider Fischer Meyer Weber \
                            Schulz Becker Hoffmann'.split(),
    'Japan': 'Satou Suzuki Takahashi Tanaka Watanabe Itou \
                            Nakamura Yamamoto Kobayashi Saitou'.split(),
    'Korea': 'Kwan Kangjun Kai Khong Nham Thang Pohng'.split(),
    'Thailand': 'Awut Channarong Khemkhaeng Puenthai Somchair Thuanthong'.split(),
    'Brazil': 'Silva Santos Oliveira Souza Rodrigues'.split(),
}

# just for the record, here is the meanings of the Thai names:
# Awut: "weapon"
# Channarong: "experienced warrior"
# Khemkhaeng: "strong"
# Puenthai: "gun"
# Somchair: "manly."
# Thuanthong: Thai name meaning "golden spear."

ROBBER_NICKNAMES = '''Atrocious Bloody Cruel Dragon Evil Fat Greedy Horrible
                    Immortal Jerky Killer Little Mad Nasty Opium Powerful
                    Quick Ruthless Strong Tiger Unbeatable Vicious Wild'''.split()

TURTLE_NAMES = 'Leonardo Raphael Michelangelo Donatello'.split()

CAPITAL_LETTERS = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
