ACCOMPL_EXP = 50
BASE_FIGHT_EXP = 20
BOOK_EXP = (5, 20)
DREAM1_EXP = 10
DREAM2_EXP = 20
DREAM3_EXP = 30
EXP_PER_LEVEL = 100
FIGHT_EXP_BASE = 20
HOME_TRAINING_EXP = 3
MASTER_TRAINING_EXP = 5
SCHOOL_TRAINING_EXP = 5
SPECTATE_FOREIGNER_EXP = (5, 15)

DRAW_EXP_DIVISOR = 2
LOSER_EXP_DIVISOR = 4
