# base constants
BASE_FIGHT_EXP = _BASE = 25
DRAW_EXP_DIVISOR = 2
EXP_PER_LEVEL = 100
LOSER_EXP_DIVISOR = 4

# derived
ACCOMPL_EXP = round(_BASE * 2.5)
BOOK_EXP = (round(_BASE * 0.25), _BASE)
DREAM1_EXP = round(_BASE * 0.5)
DREAM2_EXP = _BASE
DREAM3_EXP = round(_BASE * 1.5)
HOME_TRAINING_EXP = round(_BASE * 0.15)
MASTER_TRAINING_EXP = round(_BASE * 0.25)
SCHOOL_TRAINING_EXP = round(_BASE * 0.25)
SPECTATE_FOREIGNER_EXP = (round(_BASE * 0.25), round(_BASE * 0.75))
